[package]
name = "quicfs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = "0.11"
tokio = { version = "1.32", features = ["full"] }
rustls = { version = "0.21", features = ["quic"] }
anyhow = "1.0"
quicfs-common = { path = "../common" }
fuser = "0.13"
libc = "0.2"
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
