[package]
name = "quicfs-server"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = "0.10"
tokio = { version = "1.32", features = ["full"] }
rustls = { version = "0.21", features = ["quic"] }
rcgen = "0.11"
directories = "5.0"
anyhow = "1.0"
quicfs-common = { path = "../common" }
